# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ac723f905d054c2d49a1d73f80610f910b47a50bb7e712c7e1037a53e1ed34a3d33bdbdc1b6b16ed81aa435e9e5449a1610ec5a588b13958717979ee01c5285

test:
  secret_key_base: 7d32175228893dd5aeebefb017671a6e86a2d164d3f32d1e985be3bdd87758e9d42f7faa075a6cb6896ca809d13f76f5381dca6dd83fa5a43049ad66a8d7cef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
